config/routes.rb
RequestApp::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  match '/home', :to => "home#index"
  match '/browse', :to => "home#browse"
  match 'items/find', :to => "home#find"
  match 'search', :to => "items#search"
  match '/users/:user_id/items/:id/request', :to => "items#req", :as => "request_user_item"
  match 'my_requests', :to => 'requests#index'
  match 'my_items', :to => 'items#index'

  resources :users, :only => [] do
    resources :items do
      collection do
        post 'search'
      end
      member do
        post 'req'
      end
    end
    resources :requests, :only => [:index, :destroy] do
      get 'approve'
      get 'deny'
    end
  end

  authenticated :user do
    root :to =>  redirect("/home")
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :item_types, :only => [:index, :show]

  resources :buildings, :only => [:index, :show]

  resources :residences, :only => [:index, :show]

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :return_date, :start_date, :approved
  belongs_to :user
  belongs_to :item

  validates :start_date, :format => {:with => /\A\d{2}\/\d{2}\/\d{4}\z/ }
  validates :return_date, :format => {:with => /\A\d{2}\/\d{2}\/\d{4}\z/ }
  validates_presence_of :user_id, :item_id, :requester_id

  # validates_uniqueness_of :item_id, :scope => :requester_id

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @requests = Request.where(user_id: current_user.id).sort_by{|e| e[:created_at]}

    @awaiting = []
    @responded = []

    @your_requests = Request.where(requester_id: current_user.id).sort_by{|e| e[:created_at]}

    @requesters = []

    @requests.each do |req|
      @requesters.push(User.find(req.requester_id))
      if(req.approved == nil)
        @awaiting.push(req)
      else
        @responded.push(req)
      end
    end

    @index = 0

    respond_to do |format|
      format.html
      format.json { render json: @requests }
    end
  end

  def approve
    @request = Request.find(params[:request_id])
    @request.approved = true
    @request.save

    @other_requests = Request.where(user_id: @request.user_id, item_id: @request.item_id)

    start_year = @request.start_date.split("/").last
    return_year = @request.return_date.split("/").last

    @other_requests.each do |o|
      o_start_year = o.start_date.split("/").last
      o_return_year = o.return_date.split("/").last
      if( (o.start_date < @request.return_date && o.start_date > @request.start_date) || 
        (o.return_date < @request.return_date && o.return_date > @request.start_date) ||
        (o_start_year >= start_year && o_start_year < return_year) ||
        (o_return_year <= return_year && o_return_year > start_year) )
        o.approved = false
        o.save
      end
    end

    respond_to do |format|
      format.html { redirect_to my_requests_path }
      format.json { render json: @request }
    end
  end

  def deny
    @request = Request.find(params[:request_id])
    @request.approved = false
    @request.save

    respond_to do |format|
      format.html { redirect_to my_requests_path }
      format.json { render json: @request }
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to my_requests_path }
      format.json { head :no_content }
    end
  end

end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/requests/index.html.haml
%h1 Your Requests

%br

- if(@awaiting.length != 0)
  
  %h3 New Requests

  .row-fluid
    .span12
      .span2 Item
      .span2 Requester
      .span2 From
      .span2 To
      .span2 Response

    - @awaiting.each do |r|
      .span12
        .span2= r.item.name
        .span2= @requesters[@index].first_name + " " + @requesters[@index].last_name
        - @index += 1
        .span2= r.start_date
        .span2= r.return_date
        .span1{:align => "right"}  
          = link_to 'Approve', user_request_approve_path(current_user, r), :method => :get, 
            :data => { :confirm => "Are you sure you want to approve this request? \n" + r.item.name + " From: " + r.start_date + " To: " + r.return_date }
 
        .span1{:align => "left"}  
          = link_to 'Deny', user_request_deny_path(current_user, r), :method => :get, 
            :data => { :confirm => "Are you sure you want to deny this request? \n" + r.item.name + " From: " + r.start_date + " To: " + r.return_date }
- else
  %h4 No new requests!


- @index = 0

- if (@responded.length != 0)  

  %h3 Responded Requests

  .row-fluid
    .span12
      .span2 Item
      .span2 Requester
      .span2 From
      .span2 To
      .span2 Status

    - @responded.each do |r|
      .span12
        .span2= r.item.name
        .span2= @requesters[@index].first_name + " " + @requesters[@index].last_name
        - @index += 1
        .span2= r.start_date
        .span2= r.return_date
        .span2
          - if(r.approved)
            Approved
          - else
            Denied

- if(@your_requests.length != 0)
  %h3 Requests You've Made

  .row-fluid
    .span12
      .span2 Item
      .span2 Requested From
      .span2 From
      .span2 To
      .span2 Status

    - @your_requests.each do |yr|
      .span12
        .span2= yr.item.name
        .span2= yr.user.first_name + " " + yr.user.last_name
        .span2= yr.start_date
        .span2= yr.return_date
        .span2
          - if(yr.approved != nil)
            - if(yr.approved == true)
              .approved
                Request Approved!
            - else
              .denied
                Denied. =(
          - else
            Awaiting Response
        .span2= link_to 'Remove', user_request_path(current_user, yr), :method => :delete,
                    :data => { :confirm => "Are you sure you want to remove this request? \n" + yr.item.name + " From: " + yr.start_date + " To: " + yr.return_date }