config/routes.rb
RequestApp::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  match '/home', :to => "home#index"
  match '/browse', :to => "home#browse"
  match 'items/find', :to => "home#find"
  match 'search', :to => "items#search"
  match '/users/:user_id/items/:id/request', :to => "items#req", :as => "request_user_item"
  match 'my_requests', :to => 'requests#index'
  match 'my_items', :to => 'items#index'

  resources :users, :only => [] do
    resources :items do
      collection do
        post 'search'
      end
      member do
        post 'req'
      end
    end
    resources :requests, :only => [:index, :destroy] do
      get 'approve'
      get 'deny'
    end
  end

  authenticated :user do
    root :to =>  redirect("/home")
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :item_types, :only => [:index, :show]

  resources :buildings, :only => [:index, :show]

  resources :residences, :only => [:index, :show]

end

app/models/building.rb
class Building < ActiveRecord::Base
  attr_accessible :name
  belongs_to :residence
  has_many :user, :through => :residence
  validates_presence_of :residence, :name
  validates :name, :uniqueness => { :case_sensitive => false }
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buildings }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    @building = Building.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/new
  # GET /buildings/new.json
  def new
    @building = Building.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/1/edit
  def edit
    @building = Building.find(params[:id])
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(params[:building])

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: "new" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.json
  def update
    @building = Building.find(params[:id])

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.haml
= form_for @building do |f|
  - if @building.errors.any?
    #error_explanation
      %h2= "#{pluralize(@building.errors.count, "error")} prohibited this building from being saved:"
      %ul
        - @building.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :room
    = f.text_field :room
  .actions
    = f.submit 'Save'

app/views/buildings/edit.html.haml
%h1 Editing building

= render 'form'

= link_to 'Show', @building
\|
= link_to 'Back', buildings_path

app/views/buildings/index.html.haml
%h1 Listing buildings

%table
  %tr
    %th Name
    %th Room
    %th
    %th
    %th

  - @buildings.each do |building|
    %tr
      %td= building.name
      %td= building.room
      %td= link_to 'Show', building
      %td= link_to 'Edit', edit_building_path(building)
      %td= link_to 'Destroy', building, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Building', new_building_path

app/views/buildings/new.html.haml
%h1 New building

= render 'form'

= link_to 'Back', buildings_path

app/views/buildings/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @building.name
%p
  %b Room:
  = @building.room

= link_to 'Edit', edit_building_path(@building)
\|
= link_to 'Back', buildings_path