config/routes.rb
RequestApp::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  match '/home', :to => "home#index"
  match '/browse', :to => "home#browse"
  match 'items/find', :to => "home#find"
  match 'search', :to => "items#search"
  match '/users/:user_id/items/:id/request', :to => "items#req", :as => "request_user_item"
  match 'my_requests', :to => 'requests#index'
  match 'my_items', :to => 'items#index'

  resources :users, :only => [] do
    resources :items do
      collection do
        post 'search'
      end
      member do
        post 'req'
      end
    end
    resources :requests, :only => [:index, :destroy] do
      get 'approve'
      get 'deny'
    end
  end

  authenticated :user do
    root :to =>  redirect("/home")
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :item_types, :only => [:index, :show]

  resources :buildings, :only => [:index, :show]

  resources :residences, :only => [:index, :show]

end

app/models/residence.rb
class Residence < ActiveRecord::Base
  attr_accessible :name
  has_many :user
  has_many :building
  validates_presence_of :name
  validates :name, :uniqueness => { :case_sensitive => false }
end

app/controllers/residences_controller.rb
class ResidencesController < ApplicationController
  # GET /residences
  # GET /residences.json
  def index
    @residences = Residence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @residences }
    end
  end

  # GET /residences/1
  # GET /residences/1.json
  def show
    @residence = Residence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @residence }
    end
  end

  # GET /residences/new
  # GET /residences/new.json
  def new
    @residence = Residence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @residence }
    end
  end

  # GET /residences/1/edit
  def edit
    @residence = Residence.find(params[:id])
  end

  # POST /residences
  # POST /residences.json
  def create
    @residence = Residence.new(params[:residence])

    respond_to do |format|
      if @residence.save
        format.html { redirect_to @residence, notice: 'Residence was successfully created.' }
        format.json { render json: @residence, status: :created, location: @residence }
      else
        format.html { render action: "new" }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /residences/1
  # PUT /residences/1.json
  def update
    @residence = Residence.find(params[:id])

    respond_to do |format|
      if @residence.update_attributes(params[:residence])
        format.html { redirect_to @residence, notice: 'Residence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residences/1
  # DELETE /residences/1.json
  def destroy
    @residence = Residence.find(params[:id])
    @residence.destroy

    respond_to do |format|
      format.html { redirect_to residences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/residences/_form.html.haml
= form_for @residence do |f|
  - if @residence.errors.any?
    #error_explanation
      %h2= "#{pluralize(@residence.errors.count, "error")} prohibited this residence from being saved:"
      %ul
        - @residence.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/residences/edit.html.haml
%h1 Editing residence

= render 'form'

= link_to 'Show', @residence
\|
= link_to 'Back', residences_path

app/views/residences/index.html.haml
%h1 Listing residences

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @residences.each do |residence|
    %tr
      %td= residence.name
      %td= link_to 'Show', residence
      %td= link_to 'Edit', edit_residence_path(residence)
      %td= link_to 'Destroy', residence, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Residence', new_residence_path

app/views/residences/new.html.haml
%h1 New residence

= render 'form'

= link_to 'Back', residences_path

app/views/residences/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @residence.name

= link_to 'Edit', edit_residence_path(@residence)
\|
= link_to 'Back', residences_path