config/routes.rb
RequestApp::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  match '/home', :to => "home#index"
  match '/browse', :to => "home#browse"
  match 'items/find', :to => "home#find"
  match 'search', :to => "items#search"
  match '/users/:user_id/items/:id/request', :to => "items#req", :as => "request_user_item"
  match 'my_requests', :to => 'requests#index'
  match 'my_items', :to => 'items#index'

  resources :users, :only => [] do
    resources :items do
      collection do
        post 'search'
      end
      member do
        post 'req'
      end
    end
    resources :requests, :only => [:index, :destroy] do
      get 'approve'
      get 'deny'
    end
  end

  authenticated :user do
    root :to =>  redirect("/home")
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :item_types, :only => [:index, :show]

  resources :buildings, :only => [:index, :show]

  resources :residences, :only => [:index, :show]

end

app/views/layouts/_footer.html.haml
.row-fluid
  .span12
    .span6{:align => "left"}
      Request App
    .span6{:align => "right"}
      &copy 2013 Justin Dao

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
- if user_signed_in?
  .div{:class=>"nav-collapse collapse"}
    %ul.nav
      %li= link_to 'Home', root_path
      %li= link_to 'Browse', browse_path
      %li= link_to 'Your Items', my_items_path
      %li= link_to 'Your Requests', my_requests_path
      %li
        = render 'layouts/search'
      %li
        .btn-group
          %a{:class=>"btn btn-primary dropdown-toggle", "data-toggle" => "dropdown"}
            = current_user.email 
            .caret
          %ul.dropdown-menu
            %li= link_to 'Account Settings', edit_user_registration_path
            %li= link_to 'Sign out', destroy_user_session_path, :method => :delete

- else
  = link_to 'Register', new_user_registration_path
  or
  = link_to 'Sign in', new_user_session_path

app/views/layouts/_search.html.haml
= form_tag search_path, method: :post do
  = text_field_tag "search_box", nil, :placeholder => "Search...", :id => "search_box"
  = item_type_select
  = button_tag(:type => "submit", :class => "btn btn-default") do
    Search 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Request App"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application", :media => "all"
    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
            %footer.navbar.navbar-fixed-bottom
              %nav.navbar-inner
                .container
                  = render 'layouts/footer'